import { Product } from "../types/types";

const products:Product[] = [
  {
    id: '1',
    name: 'AirPods',
    shortDescription: 'Wireless Bluetooth earbuds',
    brand: 'Apple',
    category: 'Electronics',
    price: 199.99,
    countInStock: 15,
    rating: 4.5,
    numReviews: 1500,
    image: '/images/airpods.jpg',
  },
  {
    id: '2',
    name: 'Alexa',
    shortDescription: 'Voice-controlled smart speaker',
    brand: 'Amazon',
    category: 'Electronics',
    price: 49.99,
    countInStock: 25,
    rating: 4.7,
    numReviews: 3000,
    image: '/images/alexa.jpg',
  },
  {
    id: '3',
    name: 'Camera',
    shortDescription: 'DSLR camera with high resolution',
    brand: 'Canon',
    category: 'Electronics',
    price: 499.99,
    countInStock: 10,
    rating: 4.8,
    numReviews: 1200,
    image: '/images/camera.jpg',
  },
  {
    id: '4',
    name: 'Mouse',
    shortDescription: 'Wireless optical mouse',
    brand: 'Logitech',
    category: 'Electronics',
    price: 29.99,
    countInStock: 50,
    rating: 4.6,
    numReviews: 800,
    image: '/images/mouse.jpg',
  },
  {
    id: '5',
    name: 'Phone',
    shortDescription: 'Smartphone with advanced features',
    brand: 'Samsung',
    category: 'Electronics',
    price: 899.99,
    countInStock: 20,
    rating: 4.7,
    numReviews: 2200,
    image: '/images/phone.jpg',
  },
  {
    id: '6',
    name: 'PlayStation',
    shortDescription: 'Next-generation gaming console',
    brand: 'Sony',
    category: 'Electronics',
    price: 499.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 4000,
    image: '/images/playstation.jpg',
  },
];

export default products;
